# Generated by Django 3.1.1 on 2021-01-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdId', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('schoolName', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('semester', models.PositiveIntegerField()),
            ],
        ),
    ]
