# Generated by Django 3.1.1 on 2021-01-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloId', models.CharField(max_length=10)),
                ('cloName', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crsCode', models.PositiveIntegerField()),
                ('crsName', models.CharField(max_length=100)),
                ('department', models.PositiveIntegerField()),
                ('credit', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PLO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ploId', models.CharField(max_length=10)),
                ('ploName', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crsCode', models.CharField(max_length=100)),
                ('secId', models.PositiveIntegerField()),
                ('semester', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('ploID', models.PositiveIntegerField()),
                ('cloID', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdId', models.PositiveIntegerField()),
                ('crsCode', models.CharField(max_length=100)),
                ('secId', models.PositiveIntegerField()),
                ('semester', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('ploID', models.PositiveIntegerField()),
                ('cloID', models.PositiveIntegerField()),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyId', models.PositiveIntegerField()),
                ('crsCode', models.CharField(max_length=100)),
                ('secId', models.PositiveIntegerField()),
                ('semester', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
    ]
