# Generated by Django 3.1.5 on 2021-01-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210123_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='crsCode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
