# Generated by Django 3.1.5 on 2021-01-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210125_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='school',
            field=models.CharField(max_length=40),
        ),
    ]
